trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - '*.md'

pr:
  paths:
    exclude:
      - '*.md'

jobs:
  - job: 'Test'
    strategy:
      matrix:
        Python38Linux:
          imageName: 'ubuntu-latest'
          python.version: '3.8'
        Python38Windows:
          imageName: 'windows-latest'
          python.version: '3.8'
        Python38Mac:
          imageName: 'macOS-latest'
          python.version: '3.8'
        Python39Linux:
          imageName: 'ubuntu-latest'
          python.version: '3.9'
        Python39Windows:
          imageName: 'windows-latest'
          python.version: '3.9'
        Python39Mac:
          imageName: 'macOS-latest'
          python.version: '3.9'
        Python310Linux:
          imageName: 'ubuntu-latest'
          python.version: '3.10'
        Python310Windows:
          imageName: 'windows-latest'
          python.version: '3.10'
        Python310Mac:
          imageName: 'macOS-latest'
          python.version: '3.10'
      maxParallel: 2
    pool:
      vmImage: $(imageName)

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install "cython>=0.29"
        pip install -e ".[tests, docs]"
      displayName: 'Install dependencies'

    - script: |
        pip install pytest pytest-azurepipelines
        pytest -vs --show-capture=no tests
      displayName: 'pytest'